// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBPe3xnwy3duVG3D2s8vNGcc5dudoap4',
    appId: '1:868061658612:web:ca441b4dfe77d56d6c8da1',
    messagingSenderId: '868061658612',
    projectId: 'online-class-674b8',
    authDomain: 'online-class-674b8.firebaseapp.com',
    storageBucket: 'online-class-674b8.firebasestorage.app',
    measurementId: 'G-JJ9HWF05ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLNlJUnNLxsgM1bMuyMSDimExUGb1wBc',
    appId: '1:868061658612:android:94e14d37668325826c8da1',
    messagingSenderId: '868061658612',
    projectId: 'online-class-674b8',
    storageBucket: 'online-class-674b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD-b6_wApXt4N73YN9nttz2ppfGOALCQA',
    appId: '1:868061658612:ios:0bfd2a51cd2fb5d66c8da1',
    messagingSenderId: '868061658612',
    projectId: 'online-class-674b8',
    storageBucket: 'online-class-674b8.firebasestorage.app',
    iosBundleId: 'com.example.onlineClassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD-b6_wApXt4N73YN9nttz2ppfGOALCQA',
    appId: '1:868061658612:ios:0bfd2a51cd2fb5d66c8da1',
    messagingSenderId: '868061658612',
    projectId: 'online-class-674b8',
    storageBucket: 'online-class-674b8.firebasestorage.app',
    iosBundleId: 'com.example.onlineClassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeBPe3xnwy3duVG3D2s8vNGcc5dudoap4',
    appId: '1:868061658612:web:b7aa03fa129e45d66c8da1',
    messagingSenderId: '868061658612',
    projectId: 'online-class-674b8',
    authDomain: 'online-class-674b8.firebaseapp.com',
    storageBucket: 'online-class-674b8.firebasestorage.app',
    measurementId: 'G-RGTJ0ZE42Y',
  );
}
